/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cnc.gcode.controller;
import cnc.gcode.controller.communication.Communication;
import cnc.gcode.controller.communication.IReceivedLines;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Nutz95
 */
public class JPanelSimpleControls extends javax.swing.JPanel implements IGUIEvent{
    //private boolean parseNextSerial = false;
    private IEvent GUIEvent=null;
    private MySwingWorker worker=null;
    
    
    //X:2.00Y:0.00Z:0.00E:0.00 Count X: 1.01Y:0.00Z:0.00


    public JPanelSimpleControls() {
        initComponents();
        
        Communication.addReceiveEvent(new IReceivedLines() {
            @Override
            public void received(String[] lines) {
                for(String line: lines)
                {
                    String in   = line;
                    if((line.toLowerCase().contains("ok") == true && FilterOk.isSelected() == true) == false )
                    {
                        appendToConsole(line);
                    }
                }
            }
        });
    }

    
    private void appendToConsole(String text)
    {
        String[] lines=ConsoleOutput.getText().split("\n\r");
        String newtext="";
        for(int i=Math.max(0, lines.length-18);i<lines.length;i++)
            if(!lines[i].equals(""))
                newtext+=lines[i]+"\n\r";
        newtext+=text;
        ConsoleOutput.setText(newtext);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ZPlus10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ZPlus5 = new javax.swing.JButton();
        ZPlus1 = new javax.swing.JButton();
        ZPlus01 = new javax.swing.JButton();
        HomeZ = new javax.swing.JButton();
        ZMinus01 = new javax.swing.JButton();
        ZMinus1 = new javax.swing.JButton();
        ZMinus5 = new javax.swing.JButton();
        ZMinus10 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        XMinus10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        XMinus1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        XMinus01 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        HomeX = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        HomeY = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        YPlus10 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        YPlus01 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        YPlus1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        HomeXY = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        HomeAll = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        YMinus01 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        YMinus1 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        YMinus10 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        HomeZ2 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        XPlus01 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        XPlus10 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        XPlus1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        MotorsOff = new javax.swing.JButton();
        CurrentPos = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ConsoleOutput = new javax.swing.JTextArea();
        ClearConsole = new javax.swing.JButton();
        FilterOk = new javax.swing.JCheckBox();
        jBCancel = new javax.swing.JButton();
        MotorsOn = new javax.swing.JButton();

        setName("jBasicControls"); // NOI18N

        ZPlus10.setText("+10");
        ZPlus10.setName("ZPlus10"); // NOI18N
        ZPlus10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Z");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ZPlus5.setLabel("+5");
        ZPlus5.setName("ZPlus5"); // NOI18N
        ZPlus5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        ZPlus1.setLabel("+1");
        ZPlus1.setName("ZPlus1"); // NOI18N
        ZPlus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        ZPlus01.setLabel("+0.1");
        ZPlus01.setName("ZPlus01"); // NOI18N
        ZPlus01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        HomeZ.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        HomeZ.setText("Home");
        HomeZ.setName("HomeZ"); // NOI18N
        HomeZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        ZMinus01.setLabel("-0.1");
        ZMinus01.setName("ZMinus01"); // NOI18N
        ZMinus01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        ZMinus1.setLabel("-1");
        ZMinus1.setName("ZMinus1"); // NOI18N
        ZMinus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        ZMinus5.setLabel("-5");
        ZMinus5.setName("ZMinus5"); // NOI18N
        ZMinus5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        ZMinus10.setLabel("-10");
        ZMinus10.setName("ZMinus10"); // NOI18N
        ZMinus10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel1.setBackground(new java.awt.Color(0, 255, 72));
        jPanel1.setPreferredSize(new java.awt.Dimension(38, 124));

        XMinus10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        XMinus10.setText("-10");
        XMinus10.setName("LXMinus10"); // NOI18N
        XMinus10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lableMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(XMinus10, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(XMinus10, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(124, 255, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(38, 124));

        XMinus1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        XMinus1.setText("-1");
        XMinus1.setName("LXMinus1"); // NOI18N
        XMinus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lableMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(XMinus1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(XMinus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel14.setBackground(new java.awt.Color(221, 250, 1));
        jPanel14.setPreferredSize(new java.awt.Dimension(38, 124));

        XMinus01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        XMinus01.setText("-0.1");
        XMinus01.setName("LXMinus01"); // NOI18N
        XMinus01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lableMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(XMinus01, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(XMinus01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(java.awt.Color.red);

        HomeX.setBackground(java.awt.Color.red);
        HomeX.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        HomeX.setForeground(new java.awt.Color(254, 254, 254));
        HomeX.setText("Home X");
        HomeX.setBorderPainted(false);
        HomeX.setName("BHomeX"); // NOI18N
        HomeX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeX, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeX, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );

        jPanel8.setBackground(java.awt.Color.green);

        HomeY.setBackground(java.awt.Color.green);
        HomeY.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        HomeY.setForeground(new java.awt.Color(254, 254, 254));
        HomeY.setText("Home Y");
        HomeY.setBorderPainted(false);
        HomeY.setName("BHomeY"); // NOI18N
        HomeY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeY, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );

        jPanel18.setBackground(new java.awt.Color(0, 255, 72));
        jPanel18.setPreferredSize(new java.awt.Dimension(38, 124));

        YPlus10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        YPlus10.setText("+10");
        YPlus10.setName("LYPlus10"); // NOI18N
        YPlus10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lableMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(YPlus10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(YPlus10, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel19.setBackground(new java.awt.Color(221, 250, 1));
        jPanel19.setToolTipText("");
        jPanel19.setName(""); // NOI18N
        jPanel19.setPreferredSize(new java.awt.Dimension(38, 124));

        YPlus01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        YPlus01.setText("+0.1");
        YPlus01.setName("LYPlus01"); // NOI18N
        YPlus01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lableMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(YPlus01, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(YPlus01, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel20.setBackground(new java.awt.Color(124, 255, 0));
        jPanel20.setPreferredSize(new java.awt.Dimension(38, 124));

        YPlus1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        YPlus1.setText("+1");
        YPlus1.setName("LYPlus1"); // NOI18N
        YPlus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lableMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(YPlus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(YPlus1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.setBackground(java.awt.Color.lightGray);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("+Y");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("-Y");

        jLabel4.setText("-X");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("+X");
        jLabel5.setToolTipText("");

        jPanel6.setBackground(java.awt.Color.gray);

        HomeXY.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        HomeXY.setForeground(new java.awt.Color(254, 254, 254));
        HomeXY.setText("Home X Y");
        HomeXY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lableMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeXY, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeXY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3))
        );

        jPanel10.setBackground(new java.awt.Color(0, 255, 185));

        HomeAll.setBackground(new java.awt.Color(255, 255, 0));
        HomeAll.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        HomeAll.setForeground(new java.awt.Color(254, 254, 254));
        HomeAll.setText("Home All");
        HomeAll.setBorderPainted(false);
        HomeAll.setName("BHomeAll"); // NOI18N
        HomeAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeAll, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );

        jPanel21.setBackground(new java.awt.Color(221, 250, 1));
        jPanel21.setPreferredSize(new java.awt.Dimension(38, 124));

        YMinus01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        YMinus01.setText("-0.1");
        YMinus01.setName("LYMinus01"); // NOI18N
        YMinus01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lableMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(YMinus01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(YMinus01, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel22.setBackground(new java.awt.Color(124, 255, 0));
        jPanel22.setPreferredSize(new java.awt.Dimension(38, 124));

        YMinus1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        YMinus1.setText("-1");
        YMinus1.setName("LYMinus1"); // NOI18N
        YMinus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lableMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(YMinus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(YMinus1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel23.setBackground(new java.awt.Color(0, 255, 72));
        jPanel23.setToolTipText("");
        jPanel23.setPreferredSize(new java.awt.Dimension(38, 124));

        YMinus10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        YMinus10.setText("-10");
        YMinus10.setToolTipText("");
        YMinus10.setName("LYMinus10"); // NOI18N
        YMinus10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lableMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(YMinus10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(YMinus10, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel12.setBackground(java.awt.Color.blue);

        HomeZ2.setBackground(java.awt.Color.blue);
        HomeZ2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        HomeZ2.setForeground(new java.awt.Color(254, 254, 254));
        HomeZ2.setText("Home Z");
        HomeZ2.setBorderPainted(false);
        HomeZ2.setName("BHomeZ"); // NOI18N
        HomeZ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeZ2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeZ2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );

        jPanel15.setBackground(new java.awt.Color(221, 250, 1));
        jPanel15.setPreferredSize(new java.awt.Dimension(38, 124));

        XPlus01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        XPlus01.setText("+0.1");
        XPlus01.setName("LXPlus01"); // NOI18N
        XPlus01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lableMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(XPlus01, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(XPlus01, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );

        jPanel16.setBackground(new java.awt.Color(0, 255, 72));
        jPanel16.setPreferredSize(new java.awt.Dimension(38, 124));

        XPlus10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        XPlus10.setText("+10");
        XPlus10.setName("LXPlus10"); // NOI18N
        XPlus10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lableMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(XPlus10, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(XPlus10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel17.setBackground(new java.awt.Color(124, 255, 0));
        jPanel17.setPreferredSize(new java.awt.Dimension(38, 124));

        XPlus1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        XPlus1.setText("+1");
        XPlus1.setName("LXPlus1"); // NOI18N
        XPlus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lableMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(XPlus1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(XPlus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        MotorsOff.setText("Motors Off");
        MotorsOff.setName("BMotorsOff"); // NOI18N
        MotorsOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        CurrentPos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CurrentPos.setText("Position: X= Y= Z=");

        ConsoleOutput.setColumns(20);
        ConsoleOutput.setRows(5);
        jScrollPane1.setViewportView(ConsoleOutput);

        ClearConsole.setText("Clear Console");
        ClearConsole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearConsoleActionPerformed(evt);
            }
        });

        FilterOk.setSelected(true);
        FilterOk.setLabel("Filter \"OK\" Feedbacks");

        jBCancel.setText("Cancel");
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(FilterOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jBCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClearConsole))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearConsole)
                    .addComponent(FilterOk)
                    .addComponent(jBCancel)))
        );

        MotorsOn.setText("Motors On");
        MotorsOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ZMinus10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ZMinus5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ZMinus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ZMinus01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HomeZ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ZPlus01, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ZPlus1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ZPlus5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ZPlus10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MotorsOff)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MotorsOn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CurrentPos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(8, 8, 8)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(MotorsOff)
                    .addComponent(CurrentPos)
                    .addComponent(MotorsOn))
                .addGap(5, 5, 5)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ZPlus10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ZPlus5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ZPlus1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ZPlus01)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HomeZ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ZMinus01)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ZMinus1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ZMinus5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ZMinus10)
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator1)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean isbussy=false;
    @Override
    public void updateGUI(boolean serial, boolean isworking) {
        setEnableAllControls(!isworking && serial);
        isbussy=isworking;
    }
    private void ClearConsoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearConsoleActionPerformed
        ConsoleOutput.setText("");
    }//GEN-LAST:event_ClearConsoleActionPerformed

    private void doAction(Object sender){
        
        if(sender.equals(HomeAll)){
                ExecuteActions(new ArrayList<String>()    {{
                                                        this.add(Communication.getdoHomingCommand());
                                                        this.add(Communication.getredPostionCommand());
                                                    }});           
        }
        else if (sender.equals(HomeX)){
                ExecuteActions(new ArrayList<String>()    {{
                                                        this.add("G28 X");
                                                        this.add(Communication.getredPostionCommand());
                                                    }});              
        }
        else if (sender.equals(HomeY)){
                ExecuteActions(new ArrayList<String>()    {{
                                                        this.add("G28 Y");
                                                        this.add(Communication.getredPostionCommand());
                                                    }});              
        }
        else if (sender.equals(HomeZ) || sender.equals(HomeZ2)){
                ExecuteActions(new ArrayList<String>()    {{
                                                        this.add("G28 Z");
                                                        this.add(Communication.getredPostionCommand());
                                                    }});              
        }
        else if (sender.equals(HomeXY)){
                ExecuteActions(new ArrayList<String>()    {{
                                                        this.add("G28 X Y");
                                                        this.add(Communication.getredPostionCommand());
                                                    }});              
        }
        else if (sender.equals(MotorsOn)){
                ExecuteActions(new ArrayList<String>(Arrays.asList(DatabaseV2.SPINDLEON.get().split("\n"))));
        }
        else if (sender.equals(MotorsOff)){
                ExecuteActions(new ArrayList<String>(Arrays.asList(DatabaseV2.SPINDLEOFF.get().split("\n"))));
        }
        else if (sender.equals(XPlus01)){
            PerformSimpleMove(0.1,Axis.X);
        }
        else if (sender.equals(XPlus1)){
            PerformSimpleMove(1,Axis.X);
        }
        else if (sender.equals(XPlus10)){
            PerformSimpleMove(10,Axis.X);
        }
        else if (sender.equals(XMinus01)){
            PerformSimpleMove(-0.1,Axis.X);
        }
        else if (sender.equals(XMinus1)){
            PerformSimpleMove(-1,Axis.X);
        }
        else if (sender.equals(XMinus10)){
            PerformSimpleMove(-10,Axis.X);
        }
        
        else if (sender.equals(YPlus01)){
            PerformSimpleMove(0.1,Axis.Y);
        }
        else if (sender.equals(YPlus1)){
            PerformSimpleMove(1,Axis.Y);
        }
        else if (sender.equals(YPlus10)){
            PerformSimpleMove(10,Axis.Y);
        }
        else if (sender.equals(YMinus01)){
            PerformSimpleMove(-0.1,Axis.Y);
        }
        else if (sender.equals(YMinus1)){
            PerformSimpleMove(-1,Axis.Y);
        }
        else if (sender.equals(YMinus10)){
            PerformSimpleMove(-10,Axis.Y);
        }
        
        else if (sender.equals(ZPlus01)){
            PerformSimpleMove(0.1,Axis.Z);
        }
        else if (sender.equals(ZPlus1)){
            PerformSimpleMove(1,Axis.Z);
        }
        else if (sender.equals(ZPlus5)){
            PerformSimpleMove(5,Axis.Z);
        }
        else if (sender.equals(ZPlus10)){
            PerformSimpleMove(10,Axis.Z);
        }
        else if (sender.equals(ZMinus01)){
            PerformSimpleMove(-0.1,Axis.Z);
        }
        else if (sender.equals(ZMinus1)){
            PerformSimpleMove(-1,Axis.Z);
        }
        else if (sender.equals(ZMinus5)){
            PerformSimpleMove(-5,Axis.Z);
        }
        else if (sender.equals(ZMinus10)){
            PerformSimpleMove(-10,Axis.Z);
        }

    }
    
    
    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        doAction(evt.getSource());
    }//GEN-LAST:event_buttonActionPerformed

    private void lableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableMouseReleased
        doAction(evt.getSource());
    }//GEN-LAST:event_lableMouseReleased

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCancelActionPerformed



    private enum Axis
    {
        X, Y, Z, E
    }
    private void PerformSimpleMove(final double distance, final Axis axis)
    {
        ExecuteActions(new ArrayList<String>()    {{
                                                this.add("G91");
                                                this.add("G0 " + axis.toString() + new DecimalFormat("#.##").format(distance).replace(",", ".") +  " F" + DatabaseV2.MAXFEEDRATE.get());
                                                this.add("G90");
                                                this.add(Communication.getredPostionCommand());
                                            }});          
    }
    
    boolean isRunning() {
        return worker!=null && !worker.isDone();
    }    
    
    private void ExecuteActions(final ArrayList<String> gcodes)
    {
        if(Communication.isBussy() || isbussy)
        {
            appendToConsole("ERROR: Another command is in progress! Or not Connected!");
            return;
        }
        worker=new MySwingWorker() {

            @Override
            protected Object doInBackground() throws Exception {
                for(String execute:gcodes)
                {
                    appendToConsole(execute);
                    if(this.isCancelled())
                    {
                        return null;
                    }

                    while(Communication.isBussy())
                    {
                        if(this.isCancelled())
                        {
                            return null;
                        }
                        try
                        {
                            Thread.sleep(1);
                        }
                        catch(InterruptedException ex)
                        {
                            return null;
                        }

                    }
                    Communication.send(execute);
                }
                return null;
            }

            @Override
            protected void done(Object rvalue, Exception ex, boolean canceled) {
                if(ex!=null){
                    appendToConsole("ERROR: " + ex.getMessage());
                    Logger.getLogger(JPanelAdvancedControl.class.getName()).log(Level.SEVERE, null, ex);
                }
                GUIEvent.fired();
            }
        };
        worker.execute();
        GUIEvent.fired();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearConsole;
    private javax.swing.JTextArea ConsoleOutput;
    private javax.swing.JLabel CurrentPos;
    private javax.swing.JCheckBox FilterOk;
    private javax.swing.JButton HomeAll;
    private javax.swing.JButton HomeX;
    private javax.swing.JLabel HomeXY;
    private javax.swing.JButton HomeY;
    private javax.swing.JButton HomeZ;
    private javax.swing.JButton HomeZ2;
    private javax.swing.JButton MotorsOff;
    private javax.swing.JButton MotorsOn;
    private javax.swing.JLabel XMinus01;
    private javax.swing.JLabel XMinus1;
    private javax.swing.JLabel XMinus10;
    private javax.swing.JLabel XPlus01;
    private javax.swing.JLabel XPlus1;
    private javax.swing.JLabel XPlus10;
    private javax.swing.JLabel YMinus01;
    private javax.swing.JLabel YMinus1;
    private javax.swing.JLabel YMinus10;
    private javax.swing.JLabel YPlus01;
    private javax.swing.JLabel YPlus1;
    private javax.swing.JLabel YPlus10;
    private javax.swing.JButton ZMinus01;
    private javax.swing.JButton ZMinus1;
    private javax.swing.JButton ZMinus10;
    private javax.swing.JButton ZMinus5;
    private javax.swing.JButton ZPlus01;
    private javax.swing.JButton ZPlus1;
    private javax.swing.JButton ZPlus10;
    private javax.swing.JButton ZPlus5;
    private javax.swing.JButton jBCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setGUIEvent(IEvent event) {
        GUIEvent = event;
    }

    private void setEnableAllControls(boolean enable)
    {
        this.HomeAll.setEnabled(enable);
        
        this.HomeX.setEnabled(enable);
        this.HomeY.setEnabled(enable);
        this.HomeXY.setEnabled(enable);
        this.HomeZ.setEnabled(enable);
        this.HomeZ2.setEnabled(enable);
        
        this.MotorsOff.setEnabled(enable);
        this.MotorsOn.setEnabled(enable);
        
        this.XMinus01.setEnabled(enable);
        this.XMinus1.setEnabled(enable);
        this.XMinus10.setEnabled(enable);
        this.XPlus01.setEnabled(enable);
        this.XPlus1.setEnabled(enable);
        this.XPlus10.setEnabled(enable);
        this.YMinus01.setEnabled(enable);
        this.YMinus1.setEnabled(enable);
        this.YMinus10.setEnabled(enable);
        this.YPlus01.setEnabled(enable);
        this.YPlus1.setEnabled(enable);
        this.YPlus10.setEnabled(enable);
        this.ZMinus01.setEnabled(enable);
        this.ZMinus1.setEnabled(enable);
        this.ZMinus5.setEnabled(enable);
        this.ZMinus10.setEnabled(enable);
        this.ZPlus01.setEnabled(enable);
        this.ZPlus1.setEnabled(enable);
        this.ZPlus5.setEnabled(enable);
        this.ZPlus10.setEnabled(enable);
        this.jBCancel.setEnabled(worker!=null && worker.isRunning());
    }

}
