/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cnc.gcode.controller;

import java.awt.GridLayout;
import java.util.LinkedList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author n.rambaud
 */
//javax.swing.JFrame
public final class JSettingsDialog extends JDialog{
    private JTextField[] valuesFields;
    private final LinkedList<ISettingFeedback> feedbackValues;
    private boolean formok=false;

    
    public static LinkedList<ISettingFeedback> DisplaySettingPanel(String panelTitle,
                                                             DatabaseV2[] ids,
                                                             double[] currentValues,
                                                             double[] minValues,
                                                             double[] maxValues,
                                                             String[] descriptions)
    {
        if(ids.length !=  currentValues.length && currentValues.length!= descriptions.length)
        {
            return null;
        }
        
        LinkedList<ISettingFeedback> settings = new LinkedList<ISettingFeedback>();
        for (int i = 0; i< currentValues.length; i++)
        {
            settings.add(new JSettingFeedback(ids[i],
                                              currentValues[i],
                                              minValues[i],
                                              maxValues[i],
                                              descriptions[i] ));
        }
        JSettingsDialog form = new JSettingsDialog(settings);
        form.setTitle(panelTitle);
        form.pack();
        form.setModal(true);
        form.setVisible(true);
        
        if(form.formok)
        {
            return form.feedbackValues;
        }
        else
        {
            return null;
        }
    }

    private JSettingsDialog(LinkedList<ISettingFeedback> feedbackValues)
    {
        super();
        setResizable(false);
        initComponents();
        this.feedbackValues = feedbackValues;
        configureDataToDisplay( feedbackValues);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JSettingsPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        JOkButton = new javax.swing.JButton();
        JCancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout JSettingsPanelLayout = new javax.swing.GroupLayout(JSettingsPanel);
        JSettingsPanel.setLayout(JSettingsPanelLayout);
        JSettingsPanelLayout.setHorizontalGroup(
            JSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JSettingsPanelLayout.setVerticalGroup(
            JSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        JOkButton.setText("OK");
        JOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOkButtonActionPerformed(evt);
            }
        });

        JCancelButton.setLabel("Cancel");
        JCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JCancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JOkButton)
                    .addComponent(JCancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean ValidateNewValue(ISettingFeedback data)
    {
        double val = data.getSettingValue();
        if(val < data.getSettingMinValue())
        {
            int answer = JOptionPane.showConfirmDialog(null,
                                                        "Setting: " + data.getSettingId().toString() + " is invalid. min value:" + data.getSettingMinValue() + "\nDo you want to adjust this value to min value?." ,
                                                        "Invalid setting",
                                                         JOptionPane.YES_NO_OPTION);
            if(answer == JOptionPane.YES_OPTION)
            {
               data.setSettingValue(data.getSettingMinValue());
            }
            else{
                return false;
            }
        }
        else if(val > data.getSettingMaxValue())
        {
            int answer = JOptionPane.showConfirmDialog(null,
                                                        "Setting: " + data.getSettingId().toString() + " is invalid. max value:" + data.getSettingMaxValue()+ "\nDo you want to adjust this value to max value?.",
                                                        "Invalid setting",
                                                        JOptionPane.YES_NO_OPTION);
            if(answer == JOptionPane.YES_OPTION)
            {
               data.setSettingValue(data.getSettingMaxValue());
            }
            else{
                return false;
            }
        }
        return true;
    }
    
    private void JOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOkButtonActionPerformed
        for(int i = 0; i < feedbackValues.size();  i++)
        {
            try
            {
                feedbackValues.get(i).setSettingValue(Double.valueOf(valuesFields[i].getText())); 
                if(!ValidateNewValue(feedbackValues.get(i)))// validating all settings before updating.
                    return;
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null,
                                            "Error when converting " + valuesFields[i].getText() + ".\nIt seems not to be a double value",
                                            "Convertion error",
                                            JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        formok=true;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_JOkButtonActionPerformed

    private void JCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCancelButtonActionPerformed
        formok=false;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_JCancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JCancelButton;
    private javax.swing.JButton JOkButton;
    private javax.swing.JPanel JSettingsPanel;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    public boolean configureDataToDisplay(LinkedList<ISettingFeedback> feedbackValues) {
        
        if( feedbackValues.size() <= 0)
        {
            return false;
        }
        if( valuesFields == null)
        {
            valuesFields = new JTextField[feedbackValues.size()];
        }
        GridLayout singleGridLayout = new GridLayout(0,1);
        JSettingsPanel.setLayout(singleGridLayout );
        for (int i = 0; i < feedbackValues.size(); i++)
        {
            double min=feedbackValues.get(i).getSettingMinValue();
            double max=feedbackValues.get(i).getSettingMaxValue();
            JTextArea description = new JTextArea(feedbackValues.get(i).getSettingDescription() + "\n"
                                                    + "min: " + (min==-Double.MAX_VALUE?"-inf":""+min) + " | "
                                                    + "max: " + (max==Double.MAX_VALUE?"-inf":""+max));
            description.setEditable(false);
            valuesFields[i] = new JTextField(String.valueOf(feedbackValues.get(i).getSettingValue()));
            JSettingsPanel.add(description);
            JSettingsPanel.add(valuesFields[i]);
        }
        
        return true;
    }

    private ISettingFeedback[] getUpdatedValues(ISettingFeedback[] feedbackValues) {
        //double[] values = new double[valuesFields.length];
        
        for( int i = 0; i < valuesFields.length; i++)
        {
            try
            {
                feedbackValues[i].setSettingValue(Double.valueOf(valuesFields[i].getText()));
            }
            catch(Exception ex)
            {
            }
        }
        
        return feedbackValues;
    }
}
